### ISSUE TITLE
Gitter 생성 - Repo 기여자들이 소통할 수 있는 채널 필요

### ISSUE THREAD

**Issue by aidan-kwon** [kr-blockchain/smart-contract-best-practices#1]
현재 기여자들이 협업할 수 있는 도구 중, 메시징 도구가 필요할 거 같습니다. 
원본인 영문 사이트에서 Gitter 를 사용에 대한 언급이 있기에 한국어 버전을 위한 Gitter 생성을 고려해도 좋을 것 같습니다.

예상 되는 Gitter 주소: https://gitter.im/kr-blockchain/smart-contract-best-practices

**Comment by baerae-colin** [comment]
https://gitter.im/smart-contract-best-practices/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by baerae-colin** [comment]
@aidan-kwon 이걸로 만들었어요!

**Comment by baerae-colin** [comment]
@aidan-kwon 해결되었다고 생각하시면 이슈 닫아주세요~!
